In [ ]:
import os
os.environ["WANDB_DISABLED"] = "true"
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import torch
from torch.nn import CrossEntropyLoss
from datasets import load_dataset
from sklearn.metrics import f1_score, accuracy_score
import numpy as np
from collections import Counter

# Device setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Model & tokenizer
model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
model.to(device)

# Load dataset
dataset = load_dataset('csv', data_files={'train': 'train.csv', 'test': 'test.csv'})

# Split train into train + validation
split = dataset['train'].train_test_split(test_size=0.1, seed=42)
train_dataset = split['train']
valid_dataset = split['test']
test_dataset = dataset['test']

# Check label distribution
def print_label_distribution(dset, name):
    labels = [int(x) for x in dset['label']]
    unique, counts = np.unique(labels, return_counts=True)
    dist = dict(zip(unique, counts))
    print(f"Label distribution in {name}: {dist}")

print_label_distribution(train_dataset, "train")
print_label_distribution(valid_dataset, "validation")
print_label_distribution(test_dataset, "test")

# Ensure labels are integers
def cast_label_to_int(example):
    example['label'] = int(example['label'])
    return example

train_dataset = train_dataset.map(cast_label_to_int)
valid_dataset = valid_dataset.map(cast_label_to_int)
test_dataset = test_dataset.map(cast_label_to_int)

# Tokenization function for paired inputs, handling None values
def tokenize_function(example):
    origin_query = [str(x) if x is not None else "" for x in example['origin_query']]
    category_path = [str(x) if x is not None else "" for x in example['category_path']]
    return tokenizer(
        origin_query,
        category_path,
        truncation=True,
        padding='max_length',
        max_length=128
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
valid_dataset = valid_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

# Set format for PyTorch
for d in [train_dataset, valid_dataset, test_dataset]:
    d.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])

# Metrics computation function
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=-1)
    f1_pos = f1_score(labels, preds, average="binary", pos_label=1)
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "f1_positive": f1_pos}

# Calculate class weights based on training labels
train_labels = [int(x) for x in train_dataset['label']]
label_counts = Counter(train_labels)
total_counts = sum(label_counts.values())
class_weights = [total_counts / label_counts[i] for i in range(2)]
weights = torch.tensor(class_weights).to(device)
print(f"Class weights: {class_weights}")

# Custom Trainer class with weighted loss
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        loss_fct = CrossEntropyLoss(weight=weights)
        loss = loss_fct(logits.view(-1, model.config.num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

# Training arguments with logging to track training progress
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1_positive",
    save_total_limit=1,
    fp16=torch.cuda.is_available(),
    logging_dir='./logs',
    logging_steps=50,
    log_level="info"
)

# Trainer initialization with the custom loss
trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

# Train model
trainer.train()

# Evaluate on test
metrics = trainer.evaluate(test_dataset)
print(f"\nFinal Metrics on Test Set: {metrics}")

# Predict on test and inspect prediction distribution
preds_output = trainer.predict(test_dataset)
logits = preds_output.predictions
preds = logits.argmax(axis=-1)
unique, counts = np.unique(preds, return_counts=True)
print(f"Prediction distribution on test set: {dict(zip(unique, counts))}")

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--xlm-roberta-base/snapshots/e73636d4f797dec63c3081bb6ed5c7b0bb3f2089/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.1",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

Using device: cuda

loading file sentencepiece.bpe.model from cache at /root/.cache/huggingface/hub/models--xlm-roberta-base/snapshots/e73636d4f797dec63c3081bb6ed5c7b0bb3f2089/sentencepiece.bpe.model
loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--xlm-roberta-base/snapshots/e73636d4f797dec63c3081bb6ed5c7b0bb3f2089/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--xlm-roberta-base/snapshots/e73636d4f797dec63c3081bb6ed5c7b0bb3f2089/tokenizer_config.json
loading file chat_template.jinja from cache at None
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--xlm-roberta-base/snapshots/e73636d4f797dec63c3081bb6ed5c7b0bb3f2089/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.1",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--xlm-roberta-base/snapshots/e73636d4f797dec63c3081bb6ed5c7b0bb3f2089/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.56.1",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

loading weights file model.safetensors from cache at /root/.cache/huggingface/hub/models--xlm-roberta-base/snapshots/e73636d4f797dec63c3081bb6ed5c7b0bb3f2089/model.safetensors
Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Label distribution in train: {np.int64(0): np.int64(6068), np.int64(1): np.int64(13112)}
Label distribution in validation: {np.int64(0): np.int64(669), np.int64(1): np.int64(1463)}
Label distribution in test: {np.int64(0): np.int64(374), np.int64(1): np.int64(810)}

Map:   0%|          | 0/19180 [00:00<?, ? examples/s]

Map:   0%|          | 0/2132 [00:00<?, ? examples/s]

Map:   0%|          | 0/1184 [00:00<?, ? examples/s]

Map:   0%|          | 0/19180 [00:00<?, ? examples/s]

Map:   0%|          | 0/2132 [00:00<?, ? examples/s]

Map:   0%|          | 0/1184 [00:00<?, ? examples/s]

PyTorch: setting up devices
average_tokens_across_devices is True but world size is 1. Setting it to False automatically.
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-4162886769.py:116: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedTrainer.__init__`. Use `processing_class` instead.
  trainer = WeightedTrainer(
Using auto half precision backend

Class weights: [3.160843770599868, 1.4627821842586943]

The following columns in the Training set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 19,180
  Num Epochs = 5
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 5,995
  Number of trainable parameters = 278,045,186

The following columns in the Evaluation set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 2132
  Batch size = 32
Saving model checkpoint to ./results/checkpoint-1199
Configuration saved in ./results/checkpoint-1199/config.json
Model weights saved in ./results/checkpoint-1199/model.safetensors
tokenizer config file saved in ./results/checkpoint-1199/tokenizer_config.json
Special tokens file saved in ./results/checkpoint-1199/special_tokens_map.json
The following columns in the Evaluation set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 2132
  Batch size = 32
Saving model checkpoint to ./results/checkpoint-2398
Configuration saved in ./results/checkpoint-2398/config.json
Model weights saved in ./results/checkpoint-2398/model.safetensors
tokenizer config file saved in ./results/checkpoint-2398/tokenizer_config.json
Special tokens file saved in ./results/checkpoint-2398/special_tokens_map.json
The following columns in the Evaluation set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 2132
  Batch size = 32
Saving model checkpoint to ./results/checkpoint-3597
Configuration saved in ./results/checkpoint-3597/config.json
Model weights saved in ./results/checkpoint-3597/model.safetensors
tokenizer config file saved in ./results/checkpoint-3597/tokenizer_config.json
Special tokens file saved in ./results/checkpoint-3597/special_tokens_map.json
Deleting older checkpoint [results/checkpoint-2398] due to args.save_total_limit
The following columns in the Evaluation set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 2132
  Batch size = 32
Saving model checkpoint to ./results/checkpoint-4796
Configuration saved in ./results/checkpoint-4796/config.json
Model weights saved in ./results/checkpoint-4796/model.safetensors
tokenizer config file saved in ./results/checkpoint-4796/tokenizer_config.json
Special tokens file saved in ./results/checkpoint-4796/special_tokens_map.json
Deleting older checkpoint [results/checkpoint-1199] due to args.save_total_limit
The following columns in the Evaluation set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 2132
  Batch size = 32
Saving model checkpoint to ./results/checkpoint-5995
Configuration saved in ./results/checkpoint-5995/config.json
Model weights saved in ./results/checkpoint-5995/model.safetensors
tokenizer config file saved in ./results/checkpoint-5995/tokenizer_config.json
Special tokens file saved in ./results/checkpoint-5995/special_tokens_map.json
Deleting older checkpoint [results/checkpoint-3597] due to args.save_total_limit


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from ./results/checkpoint-5995 (score: 0.7709766162310867).
Deleting older checkpoint [results/checkpoint-4796] due to args.save_total_limit
The following columns in the Evaluation set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 1184
  Batch size = 32

The following columns in the test set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 1184
  Batch size = 32

Final Metrics on Test Set: {'eval_loss': 0.678384006023407, 'eval_accuracy': 0.6841216216216216, 'eval_f1_positive': 0.7691358024691358, 'eval_runtime': 1.933, 'eval_samples_per_second': 612.522, 'eval_steps_per_second': 19.141, 'epoch': 5.0}
Prediction distribution on test set: {np.int64(0): np.int64(374), np.int64(1): np.int64(810)}

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report

# Run prediction on test set
predictions = trainer.predict(test_dataset)

# Convert logits to predicted class indices
pred_labels = np.argmax(predictions.predictions, axis=1)

# True labels from dataset
true_labels = predictions.label_ids

# Create a DataFrame for analysis
df_results = pd.DataFrame({
    "true_label": true_labels,
    "predicted_label": pred_labels,
    "correct": true_labels == pred_labels
})

# Display first 20 rows (or any number you like)
display(df_results.head(20))

# Optional: quick summary stats
print("Total samples:", len(df_results))
print("Number correct:", df_results['correct'].sum())
print("Accuracy:", df_results['correct'].mean())

# Confusion matrix
cm = confusion_matrix(true_labels, pred_labels)
print("\nConfusion Matrix:\n", cm)

# Classification report
report = classification_report(true_labels, pred_labels, digits=4)
print("\nClassification Report:\n",report)

The following columns in the test set don't have a corresponding argument in `XLMRobertaForSequenceClassification.forward` and have been ignored: category_path, origin_query, task, language. If category_path, origin_query, task, language are not expected by `XLMRobertaForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 1184
  Batch size = 32

    true_label  predicted_label  correct
0            1                1     True
1            1                0    False
2            0                1    False
3            1                1     True
4            1                0    False
5            1                0    False
6            1                1     True
7            1                1     True
8            1                1     True
9            0                0     True
10           1                1     True
11           1                1     True
12           1                1     True
13           1                1     True
14           1                1     True
15           1                0    False
16           1                1     True
17           1                1     True
18           1                1     True
19           1                1     True

Total samples: 1184
Number correct: 810
Accuracy: 0.6841216216216216

Confusion Matrix:
 [[187 187]
 [187 623]]

Classification Report:
               precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000       374
           1     0.7691    0.7691    0.7691       810

    accuracy                         0.6841      1184
   macro avg     0.6346    0.6346    0.6346      1184
weighted avg     0.6841    0.6841    0.6841      1184

In [ ]:
# Save model + tokenizer
model.save_pretrained("xlm_roberta_model")
tokenizer.save_pretrained("xlm_roberta_tokenizer")

# Zip them for easy download
!zip -r model_files.zip xlm_roberta_model xlm_roberta_tokenizer

Configuration saved in xlm_roberta_model/config.json
Model weights saved in xlm_roberta_model/model.safetensors
tokenizer config file saved in xlm_roberta_tokenizer/tokenizer_config.json
Special tokens file saved in xlm_roberta_tokenizer/special_tokens_map.json

  adding: xlm_roberta_model/ (stored 0%)
  adding: xlm_roberta_model/model.safetensors (deflated 24%)
  adding: xlm_roberta_model/config.json (deflated 50%)
  adding: xlm_roberta_tokenizer/ (stored 0%)
  adding: xlm_roberta_tokenizer/sentencepiece.bpe.model (deflated 49%)
  adding: xlm_roberta_tokenizer/tokenizer_config.json (deflated 76%)
  adding: xlm_roberta_tokenizer/tokenizer.json (deflated 76%)
  adding: xlm_roberta_tokenizer/special_tokens_map.json (deflated 52%)

In [ ]:
!git config --global user.email "khushiecstacysharma@gmail.com"
!git config --global user.name "KhushiSharmaUpamanyu"

In [ ]:
!git init
!git branch -M main

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/

In [ ]:
!git remote add origin https://github.com/KhushiSharmaUpamanyu/NEW-STREAMLIT-APP.git

In [ ]:
!git add app.py requirements.txt xlm_roberta_model xlm_roberta_tokenizer

In [ ]:
!git commit -m "Initial commit - Streamlit app with XLM-R model"

[main (root-commit) daed3e5] Initial commit - Streamlit app with XLM-R model
 8 files changed, 1000611 insertions(+)
 create mode 100644 app.py
 create mode 100644 requirements.txt
 create mode 100644 xlm_roberta_model/config.json
 create mode 100644 xlm_roberta_model/model.safetensors
 create mode 100644 xlm_roberta_tokenizer/sentencepiece.bpe.model
 create mode 100644 xlm_roberta_tokenizer/special_tokens_map.json
 create mode 100644 xlm_roberta_tokenizer/tokenizer.json
 create mode 100644 xlm_roberta_tokenizer/tokenizer_config.json

In [ ]:
!git pull origin main --allow-unrelated-histories

remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 878 bytes | 878.00 KiB/s, done.
From https://github.com/KhushiSharmaUpamanyu/NEW-STREAMLIT-APP
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

In [ ]:
!git add app.py requirements.txt xlm_roberta_model xlm_roberta_tokenizer

In [ ]:
!git commit -m "Add Streamlit app and model files"

On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	logs/
	model_files.zip
	results/
	sample_data/
	test.csv
	train.csv

nothing added to commit but untracked files present (use "git add" to track)

In [ ]:
!git pull origin main --rebase

From https://github.com/KhushiSharmaUpamanyu/NEW-STREAMLIT-APP
 * branch            main       -> FETCH_HEAD
Current branch main is up to date.

In [ ]:
!git push origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [ ]:
# Reset the remote with token
!git remote set-url origin https://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@github.com/KhushiSharmaUpamanyu/NEW-STREAMLIT-APP.git

# Add, commit, and push
!git add .
!git commit -m "Update from Colab"
!git push origin main

On branch main
nothing to commit, working tree clean
Enumerating objects: 62, done.
Counting objects: 100% (62/62), done.
Delta compression using up to 2 threads
Compressing objects: 100% (51/51), done.
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (61/61), 2.26 GiB | 38.00 MiB/s, done.
Total 61 (delta 8), reused 3 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

In [ ]:
!apt-get install git-lfs -y
!git lfs install

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git-lfs is already the newest version (3.0.2-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Updated git hooks.
Git LFS initialized.

In [ ]:
!git lfs install
!git lfs track "xlm_roberta_model/model.safetensors"
!git add .gitattributes
!git add xlm_roberta_model/model.safetensors
!git commit -m "Add model via Git LFS"
!git push origin main

Updated git hooks.
Git LFS initialized.
Tracking "xlm_roberta_model/model.safetensors"
[main 12a8744] Add model via Git LFS
 2 files changed, 1 insertion(+)
 create mode 100644 .gitattributes
 rewrite xlm_roberta_model/model.safetensors (99%)
Uploading LFS objects: 100% (1/1), 1.1 GB | 33 MB/s, done.
Enumerating objects: 67, done.
Counting objects: 100% (67/67), done.
Delta compression using up to 2 threads
Compressing objects: 100% (56/56), done.
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (66/66), 2.26 GiB | 38.57 MiB/s, done.
Total 66 (delta 9), reused 3 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

In [ ]:
# Make a backup branch first
!git branch backup-main

# Run BFG to remove the large file
!java -jar bfg-1.14.0.jar --delete-files model.safetensors

# Cleanup the repo
!git reflog expire --expire=now --all
!git gc --prune=now --aggressive

# Force push cleaned repo to GitHub
!git push origin main --force

Error: Unable to access jarfile bfg-1.14.0.jar
Enumerating objects: 69, done.
Counting objects: 100% (69/69), done.
Delta compression using up to 2 threads
Compressing objects: 100% (57/57), done.
Writing objects: 100% (69/69), done.
Total 69 (delta 10), reused 3 (delta 0), pack-reused 0
Uploading LFS objects: 100% (1/1), 1.1 GB | 0 B/s, done.
Enumerating objects: 69, done.
Counting objects: 100% (69/69), done.
Delta compression using up to 2 threads
Compressing objects: 100% (47/47), done.
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (69/69), 2.26 GiB | 44.33 MiB/s, done.
Total 69 (delta 10), reused 69 (delta 10), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

In [ ]:
!git rm --cached xlm_roberta_model/model.safetensors

rm 'xlm_roberta_model/model.safetensors'

In [ ]:
!git commit -m "Remove large model file from repo"

[main 03817a6] Remove large model file from repo
 1 file changed, 3 deletions(-)
 delete mode 100644 xlm_roberta_model/model.safetensors

In [ ]:
!git push origin main --force

Uploading LFS objects: 100% (1/1), 1.1 GB | 0 B/s, done.
Enumerating objects: 72, done.
Counting objects: 100% (72/72), done.
Delta compression using up to 2 threads
Compressing objects: 100% (49/49), done.
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (72/72), 2.26 GiB | 42.73 MiB/s, done.
Total 72 (delta 11), reused 68 (delta 10), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

In [ ]:
!git lfs track "xlm_roberta_model/model.safetensors"
!git add .gitattributes
!git add xlm_roberta_model/model.safetensors
!git commit -m "Add model via Git LFS"
!git push origin main

"xlm_roberta_model/model.safetensors" already supported
[main 1848ba2] Add model via Git LFS
 1 file changed, 3 insertions(+)
 create mode 100644 xlm_roberta_model/model.safetensors
Uploading LFS objects: 100% (1/1), 1.1 GB | 0 B/s, done.
To https://github.com/KhushiSharmaUpamanyu/NEW-STREAMLIT-APP.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/KhushiSharmaUpamanyu/NEW-STREAMLIT-APP.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

In [ ]:
!git fetch origin
!git pull origin main --rebase
!git push origin main

remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (6/6), done.
Unpacking objects: 100% (9/9), 3.67 KiB | 1.84 MiB/s, done.
remote: Total 9 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
From https://github.com/KhushiSharmaUpamanyu/NEW-STREAMLIT-APP
   b0d1fdf..253354d  main       -> origin/main
From https://github.com/KhushiSharmaUpamanyu/NEW-STREAMLIT-APP
 * branch            main       -> FETCH_HEAD
Successfully rebased and updated refs/heads/main.
Enumerating objects: 71, done.
Counting objects: 100% (71/71), done.
Delta compression using up to 2 threads
Compressing objects: 100% (51/51), done.
^C